on: [push]

jobs:
  create_staging_repository:
    runs-on: ubuntu-latest
    name: Create staging repository
    steps:
    - name: 
      id: create
      uses: martinbonnin/create-nexus-staging-repo@main
      with:
        username: ${{ secrets.SONATYPE_USERNAME }}
        password: ${{ secrets.SONATYPE_PASSWORD }}
        staging-profile-id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        description: A test staging repository from Actio
    - name: 
      run: echo "Repository created with id ${{ steps.create.outputs.repository-id }}"