on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repositoryid: ${{ steps.create.outputs.repositoryid }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - name: 
      id: create
      uses: martinbonnin/create-nexus-staging-repo@main
      with:
        username: ${{ secrets.SONATYPE_USERNAME }}
        password: ${{ secrets.SONATYPE_PASSWORD }}
        staging-profile-id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        description: A test staging repository from Actions
    - name: 
      run: echo "Repository created with id ${{ steps.create.outputs.repositoryid }}"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    name: Upload file in staging repo
    steps:
    - name: 
      run: echo "The created repository is ${{ needs.job1.outputs.repositoryid }} ${{needs.job1.outputs.output2}}"

