on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repository-id: ${{ steps.create.outputs.repository-id }}
    steps:
    - name: 
      id: create
      uses: martinbonnin/create-nexus-staging-repo@main
      with:
        username: mbonnin # Do not use secrets since the repository id will contain it and it will not be passed accross jobs
        password: ${{ secrets.SONATYPE_PASSWORD }}
        staging-profile-id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        description: A test staging repository from Actions
  job2:
    runs-on: ubuntu-latest
    needs: job1
    name: Display repo
    steps:
    - name: 
      run: echo "The created repository is ${{ needs.job1.outputs.repository-id }}"

