on: [push]

jobs:
  create_staging_repository:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repository-id: ${{ steps.create.outputs.repository-id }}
    steps:
    - id: create
      uses: martinbonnin/create-nexus-staging-repo@main
      with:
        # Do not use secrets for the username since the repository id will contain it
        # and it will not be passed across jobs :/
        username: mbonnin
        password: ${{ secrets.SONATYPE_PASSWORD }}
        staging-profile-id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        description: Created by $GITHUB_WORKFLOW ($GITHUB_ACTION) for $GITHUB_REPOSITORY

  macOS:
    runs-on: macOS-latest
    needs: create_staging_repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Publish
        run: |
          ./gradlew publishToOss
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository-id }}
          SONATYPE_USERNAME: mbonnin
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

  windows:
    runs-on: windows-latest
    needs: create_staging_repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Publish
        run: |
          ./gradlew publishMingwX64PublicationToOss
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository-id }}
          SONATYPE_USERNAME: mbonnin
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
